[package]
name = "lark-webhook-notify-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "lark-webhook-notify"
path = "src/main.rs"

[dependencies]
lark-webhook-notify = { path = "../lark-webhook-notify", version = "0.1.1" }
clap = { version = "4", features = ["derive"] }
serde_json = "1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
